-- THIS FILE WAS GENERATED BY scripts/build-spawn-decks.py
-- ALL MANUAL CHANGES WILL BE LOST THE NEXT TIME THIS FILE IS GENERATED!

local commitHash = "b09a1641cc3ae7e1a8d1c13dfdf717e45909ae9e"
local index = {
	{ name = "Milestone Campaign League", path = "mcl-decks.lua", category = "custom" },
	{ name = "2026 Playtest (november)", path = "2026-november.lua", category = "playtest" },
	{ name = "2026 Playtest (v01)", path = "2026-v01.lua", category = "playtest" },
}