-- THIS FILE WAS GENERATED BY scripts/build-spawn-decks.py
-- ALL MANUAL CHANGES WILL BE LOST THE NEXT TIME THIS FILE IS GENERATED!

local commitHash = "dadd57dddf7c972c8dae3d085837d584f1e55be7"
local index = {
	{ name = "Milestone Campaign League", path = "mcl-decks.lua", category = "custom" },
	{ name = "2026 Playtest (v01)", path = "2026-v01.lua", category = "playtest" },
	{ name = "2026 Playtest (november)", path = "2026-november.lua", category = "playtest" },
	{ name = "2026 Playtest (january-v1)", path = "2026-january-v1.lua", category = "playtest" },
	{ name = "2026 Playtest (february)", path = "2026-february.lua", category = "playtest" },
}